# Generated by Django 4.1.10 on 2023-07-12 16:59

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('space_agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_galery', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
