# Generated by Django 4.1.10 on 2023-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='galery',
            name='name',
            field=models.CharField(blank=True, default='Название не было добавлено', max_length=50, verbose_name='Название изображения'),
        ),
    ]
