# Generated by Django 4.1.10 on 2023-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_agency', '0002_alter_galery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='name',
            field=models.CharField(blank=True, default='Без названия', max_length=50, verbose_name='Название изображения'),
        ),
    ]
